volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
